DELIMITER |
DROP FUNCTION IF EXISTS BINARIZE_UUID;
CREATE FUNCTION BINARIZE_UUID(uuid CHAR(36))
RETURNS BINARY(16) DETERMINISTIC
RETURN UNHEX(
CONCAT(SUBSTR(uuid, 25), 
CONCAT(SUBSTR(uuid,20,4),
CONCAT(SUBSTR(uuid, 15,4),
CONCAT(SUBSTR(uuid, 10, 4),
REVERSE(SUBSTR(uuid,1,8))
)
)
)
)
);
|
DELIMITER ;
DELIMITER |
DROP FUNCTION IF EXISTS UNBINARIZE_UUID;
CREATE FUNCTION UNBINARIZE_UUID(buuid BINARY(16))
RETURNS CHAR(36) DETERMINISTIC
 
BEGIN
DECLARE uuid char(32);
DECLARE p1 char(8);
DECLARE p2 char(4);
DECLARE p3 char(4);
DECLARE p4 char(4);
DECLARE p5 char(12);
SET uuid = HEX(buuid);
SET p1 = REVERSE(SUBSTR(uuid,25));
SET p2 = SUBSTR(uuid,21,4);
SET p3 = SUBSTR(uuid,17,4);
set p4 = SUBSTR(uuid,13,4);
set p5 = SUBSTR(uuid,1,12);
RETURN LOWER(CONCAT(p1,CONCAT('-',CONCAT(p2,CONCAT('-',CONCAT(p3,CONCAT('-',CONCAT(p4,CONCAT('-',p5)))))))));
 

END |
DELIMITER ;

